name: Build Chromium

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check disk space
        run: df -h

      - name: Remove extra software
        run: |
          sudo apt-get purge -y firefox
          sudo rm -rf /usr/local/share/chromium
          sudo apt-get purge -y mongodb-org
          sudo apt-get purge -y apache2
          sudo rm -rf /usr/share/swift
          sudo apt-get purge -y moby-engine moby-cli moby-buildx moby-compose
          sudo apt-get purge -y podman buildah skopeo
          sudo apt-get purge -y esl-erlang
          sudo rm -rf /usr/local/bin/rebar3

      - name: Check disk space
        run: df -h

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - uses: actions/checkout@v2

      - name: Fetch depot_tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Fetch Chromium source
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          mkdir chromium
          cd chromium
          fetch --nohooks chromium

      - name: Check disk space
        run: df -h

      - name: Install build deps
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          cd chromium/src
          ./build/install-build-deps.sh

      - name: gclient runhooks
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          cd chromium/src
          gclient runhooks

      - name: Generate default config
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          cd chromium/src
          gn gen out/Default

      - name: Build
        run: |
          export PATH="$PATH:$PWD/depot_tools"
          cd chromium/src
          autoninja -C out/Default chrome

      - uses: actions/upload-artifact@v2
        with:
          name: out/Default
          path: chromium/src/out/Default

